### ISSUE TITLE
HSQLDB数据库认证

### ISSUE THREAD

**Issue by laomazi2006** [laomazi2006/sso#1]
1. HSQLDB文件数据库存储在sso-server进行加载用户数据
2. 密码策略为MD5+盐进行测试
3. 新增单元测试对数据库进行测试

**Comment by laomazi2006** [comment]
1. MD5+盐的方式，目前默认提供的不允许加盐，允许加密钥
2. 测试的还不能通过spring-boot-starter-jdbc进行测试，后面是需要解决的

嵌入式数据库默认用户提供如下：
* admin/123 可登录
* test/12345678 可登录
* test_l/1234 锁定
* test_d/12345 不可用，需要修改密码

**Comment by BinyangChen** [comment]
楼主 你好！我修改了mysql链接我自己的数据库，密码加盐用的是用户表的一个字段，请问怎么配置密码呢？
