### ISSUE TITLE
密码找回

### ISSUE THREAD

**Issue by liuhao0813** [laomazi2006/sso#21]
密码找回功能

**Comment by laomazi2006** [comment]
@liuhao0813 cas有提供相关的找回密码功能，计划在1.6.0集成并且输出教程

**Comment by laomazi2006** [comment]
功能已添加，最新点已提交
目前发现有小问题，修改密码成功但数据没有发生改变，而update语句已经执行，可以连接到mysql或者其他数据库尝试
