### ISSUE TITLE
调用单点注销地址，能否注销掉业务系统的session?

### ISSUE THREAD

**Issue by ahai1980** [laomazi2006/sso#29]
麻烦问下，我直接调用单点的注销地址（https://*****/cas/logout），能否有办法注销掉业务系统的session?我发现如果业务系统的session不注销，仍然会进入业务系统。

**Comment by laomazi2006** [comment]
cas原理是，当客户端发出注销请求时，找到对应TGT的ST以及所有的service，他会对所有的service携带者一个id发出通知，目前我试过cas-client单点注销是 没问题的，但集成shiro-pac4j就不行了，当然可以参考一下我的这篇博文http://blog.csdn.net/u010475041/article/details/78234027

**Comment by ahai1980** [comment]
明白了，非常感谢，开始以为service里配置的logout地址，一定是应用的单点注销地址，其实不用。还是要在cas-client配置注销的监听才可以。
